import { useMemo, useState } from 'react';
import { Download, Printer, X } from 'lucide-react';
import { CITIES } from '../../data/staticData';
import { getCityName } from '../../utils/bookingHelpers';
import { getPaymentMethodLabel, getPaymentStatusLabel } from '../../utils/paymentHelpers';
import { usePaymentSettings } from '../../hooks/usePaymentSettings';

const escapeHtml = (value) => String(value ?? '').replace(/[&<>"']/g, (char) => ({
  '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#039;',
}[char]));

function createInvoiceHtml({ booking, orderDisplayId, lang, companyName, note }) {
  const isAr = lang === 'ar';
  const dir = isAr ? 'rtl' : 'ltr';
  const route = `${getCityName(CITIES, booking.from, lang)} → ${getCityName(CITIES, booking.to, lang)}`;
  const amount = booking.totalPrice || booking.price || '—';
  const rows = [
    [isAr ? 'رقم الفاتورة' : 'Invoice number', `#${orderDisplayId}`],
    [isAr ? 'اسم العميل' : 'Customer', booking.customerName || '—'],
    [isAr ? 'البريد الإلكتروني' : 'Email', booking.customerEmail || '—'],
    [isAr ? 'الهاتف' : 'Phone', booking.customerPhone || '—'],
    [isAr ? 'المسار' : 'Route', route],
    [isAr ? 'التاريخ والوقت' : 'Date & time', [booking.date, booking.time].filter(Boolean).join(' ') || '—'],
    [isAr ? 'طريقة الدفع' : 'Payment method', getPaymentMethodLabel(booking.paymentMethod || 'bank_transfer', lang)],
    [isAr ? 'حالة الدفع' : 'Payment status', getPaymentStatusLabel(booking.paymentStatus || 'pending', lang)],
  ];

  return `<!doctype html>
<html lang="${lang}" dir="${dir}"><head><meta charset="utf-8"><title>${isAr ? 'فاتورة' : 'Invoice'} #${escapeHtml(orderDisplayId)}</title>
<style>body{font-family:Arial,sans-serif;color:#15221f;margin:40px;line-height:1.5}.invoice{max-width:760px;margin:auto}.head{background:#0b5345;color:#fff;padding:28px;border-radius:14px}.head h1{margin:0;font-size:28px}.meta{margin-top:8px;opacity:.9}table{width:100%;border-collapse:collapse;margin:26px 0}td{border-bottom:1px solid #e5e7eb;padding:12px 8px}td:first-child{color:#667085;font-weight:bold;width:42%}.total{font-size:21px;font-weight:bold;text-align:${isAr ? 'left' : 'right'};padding:16px;background:#f0f8f5;border-radius:10px}.note{margin-top:28px;color:#475467;white-space:pre-wrap}.footer{margin-top:40px;text-align:center;color:#667085;font-size:12px}</style>
</head><body><main class="invoice"><header class="head"><h1>${escapeHtml(companyName)}</h1><div class="meta">${isAr ? 'فاتورة طلب / دفع' : 'Order / Payment Invoice'} · #${escapeHtml(orderDisplayId)}</div></header>
<table>${rows.map(([label, value]) => `<tr><td>${escapeHtml(label)}</td><td>${escapeHtml(value)}</td></tr>`).join('')}</table>
<div class="total">${isAr ? 'الإجمالي' : 'Total'}: ${escapeHtml(amount)} SAR</div>
${note ? `<div class="note">${escapeHtml(note)}</div>` : ''}
<footer class="footer">${isAr ? 'هذه فاتورة صادرة من النظام.' : 'This invoice was generated by the system.'}</footer></main></body></html>`;
}

export default function OrderInvoiceModal({ booking, orderDisplayId, open, onClose }) {
  const { settings } = usePaymentSettings();
  const [lang, setLang] = useState('ar');
  const [companyName, setCompanyName] = useState('');
  const [note, setNote] = useState('');
  const defaultName = settings?.email?.brandName?.[lang] || (lang === 'ar' ? 'بشاير العطاء' : 'Bashayer Al-Ataa');
  const html = useMemo(() => createInvoiceHtml({
    booking,
    orderDisplayId,
    lang,
    companyName: companyName || defaultName,
    note,
  }), [booking, orderDisplayId, lang, companyName, defaultName, note]);

  if (!open || !booking) return null;

  const printInvoice = () => {
    const popup = window.open('', '_blank');
    if (!popup) return;
    popup.document.write(html);
    popup.document.close();
    popup.focus();
    popup.print();
  };

  const downloadInvoice = () => {
    const blob = new Blob([html], { type: 'text/html;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const anchor = document.createElement('a');
    anchor.href = url;
    anchor.download = `invoice-${orderDisplayId}-${lang}.html`;
    anchor.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="fixed inset-0 z-[10000] flex items-end sm:items-center justify-center p-0 sm:p-4">
      <div className="absolute inset-0 bg-dark-900/60 backdrop-blur-sm" onClick={onClose} />
      <div className="relative w-full sm:max-w-xl max-h-[92vh] overflow-y-auto bg-white dark:bg-dark-800 rounded-t-3xl sm:rounded-3xl shadow-2xl p-5 space-y-4">
        <div className="flex items-center justify-between gap-3">
          <div><p className="text-xs text-gray-500">#{orderDisplayId}</p><h2 className="text-lg font-black">{lang === 'ar' ? 'فاتورة الطلب والدفع' : 'Order & Payment Invoice'}</h2></div>
          <button type="button" onClick={onClose} className="p-2 rounded-xl hover:bg-gray-100 dark:hover:bg-dark-700"><X className="w-5 h-5" /></button>
        </div>
        <div className="flex gap-2">
          {['ar', 'en'].map((value) => <button key={value} type="button" onClick={() => setLang(value)} className={`flex-1 py-2 rounded-xl text-sm font-bold ${lang === value ? 'bg-primary-600 text-white' : 'bg-gray-100 dark:bg-dark-700'}`}>{value === 'ar' ? 'العربية' : 'English'}</button>)}
        </div>
        <input value={companyName} onChange={(e) => setCompanyName(e.target.value)} placeholder={defaultName} dir={lang === 'ar' ? 'rtl' : 'ltr'} className="w-full px-4 py-2.5 rounded-xl border border-gray-200 dark:border-dark-600 bg-white dark:bg-dark-700 text-sm" />
        <textarea value={note} onChange={(e) => setNote(e.target.value)} placeholder={lang === 'ar' ? 'ملاحظة على الفاتورة (اختياري)' : 'Invoice note (optional)'} dir={lang === 'ar' ? 'rtl' : 'ltr'} rows={3} className="w-full px-4 py-2.5 rounded-xl border border-gray-200 dark:border-dark-600 bg-white dark:bg-dark-700 text-sm" />
        <div className="flex gap-3">
          <button type="button" onClick={printInvoice} className="flex-1 inline-flex items-center justify-center gap-2 py-3 rounded-xl bg-primary-600 text-white font-bold"><Printer className="w-4 h-4" />{lang === 'ar' ? 'طباعة' : 'Print'}</button>
          <button type="button" onClick={downloadInvoice} className="flex-1 inline-flex items-center justify-center gap-2 py-3 rounded-xl border border-primary-300 text-primary-700 dark:text-primary-300 font-bold"><Download className="w-4 h-4" />{lang === 'ar' ? 'تحميل' : 'Download'}</button>
        </div>
      </div>
    </div>
  );
}
